[package]
name = "ziro"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
sysinfo = "0.31"
inquire = "0.7"
anyhow = "1.0"
colored = "2.1"
tabled = "0.15"
